application: mennypersonalsite
version: 1
runtime: python
api_version: 1

handlers:
- url: /static/([^/]+)/(.*)
  static_files: themes/\1/\2
  upload: themes/[^/]+/static/.*
  
- url: .*
  script: main.py
